### ISSUE TITLE
Add beta of issues module into the app

### ISSUE THREAD

**Issue by OneLiL05** [OneLiL05/onedo#29]
**TODO:**

---

- [ ] Add issue item component;
- [ ] Add issue filters;
- [ ] Add priority of issue;
- [ ] Add issue's badges
